/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/media/glassshards.glb 
*/

import { useControls } from "leva";
import { Float, MeshTransmissionMaterial, useGLTF } from "@react-three/drei";

export function GlassShards(props: any) {
  const { nodes } = useGLTF("/media/glass.glb");

  return (
    <group {...props} dispose={null}>
      {nodes.Scene.children.map((mesh, index) => {
        return <Mesh props={mesh} key={index} />;
      })}
    </group>
  );
}

useGLTF.preload("/media/glass.glb");

function Mesh({ props }: any) {
  const options = {
    thickness: { value: 0.275, min: 0, max: 1, step: 0.01 },
    ior: { value: 1.8, min: 0, max: 3, step: 0.1 },
    chromaticAberration: { value: 0.75, min: 0, max: 1 },
    resolution: { value: 300 },
  };
  const levaControls = useControls("MeshTransmissionMaterial", options);
  return (
    <Float>
      <mesh {...props}>
        <MeshTransmissionMaterial
          roughness={0}
          transmission={0.99}
          {...levaControls}
          // thickness={0.275}
          // ior={1.8}
          // chromaticAberration={0.75}
          // resolution={300}
        />
      </mesh>
    </Float>
  );
}
